### ISSUE TITLE
single apostrophes get changed into quote marks

### ISSUE THREAD

**Issue by joshuasorkin** [shotstack-samples/build-me-a-video-twitter-bot#7]
to replicate:

1. post a tweet with the text **Hello's World**.
2. reply to the tweet with **@buildMeAVideo**
3. A video gets posted with the text **Hello"s World**

**Comment by joshuasorkin** [comment]
The problem is in https://github.com/shotstack-samples/build-me-a-video-twitter-bot/blob/main/handlers/process/lib/render.js, line 13:

`  newString = string.replace(/'/g, '&quot;');`

This should instead be:

`  newString = string.replace(/'/g, '&apos;');`

or

`  newString = string.replace(/'/g, '&#x2019;');`

The latter is if you want to use a curly apostrophe ( **’** ), which I think actually looks more professional in the final render.  Interestingly, actually using a curly apostrophe in the tweet is a workaround, as it isn't a reserved character and passes through the render function unchanged.

This is a really easy fix; I'd be happy to submit a PR for this if you like.

**Comment by Forpetesake2** [comment]
Good pickup. Didn't think of that one. 

Yeah feel free submit a PR and I'll merge and deploy.

**Comment by joshuasorkin** [comment]
I'm getting a 403 on my end when I try `git push origin apostrophe-fix`; maybe you have to add me to the repo as a contributor?

EDIT: never mind, I forked it and pushed to my remote instead of trying to push to yours, and that solved the problem

**Comment by joshuasorkin** [comment]
> Good pickup. Didn't think of that one.
> 
> Yeah feel free submit a PR and I'll merge and deploy.

PR submitted.

**Comment by Forpetesake2** [comment]
Sweet thanks. Have merged and deployed. Changes are now live!
